#!/usr/bin/env bash
# This script is displaying "Best School" 9 times
# and "hi" 1 time at nine iteration
# Shellcheck style wants dummy _ variable if not used

n=0
while [ $n -le 9 ]
do
  if [ $n -eq 8 ]
  then
    echo "Best School"
    echo "Hi"
  else
   echo "Best School"
  fi
  (( n++ ))
done
