#!/usr/bin/env bash
# This script is displaying "Best School" 9 times and "hi" 1 time at nine iteration

n=1
while [ $n -le 10 ]
do
  if [ $n -eq 9 ]
  then
    echo -e "Best School\nHi"
  else
    echo "Best School"
  fi
  (( n++ ))
done
