#!/usr/bin/env bash
# This bash script ping ip 5 times if argumnet provided
# or displat message "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}" if not provided

if [ $# -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
